### ISSUE TITLE
Nothing showed up in after executing ./cube

### ISSUE THREAD

**Issue by hilmiwicak** [leonmavr/retrocube#1]
I've successfully built the file, although it has some arbitrary errors (like `obj_plane_z_at_xy declared but never defined`), but it builds just fine. The real problem is nothing showed up after executing `./cube`. At first I thought it was because I was in terminal that has theme and I'm running the file inside tmux, but it's the same after using a different terminal. I'm guessing it has something to do with `libncurses`. I've tried using `libncurses5-dev` and `libncurses` and nothing works. I'm using Ubuntu 20.04.

**Comment by leonmavr** [comment]
Thanks for reporting it. I haven't tried it on Ubuntu 20. I had the same issue on termite but then I switched to alacritty and it showed up. I will try it myself and tmux and let you know. It probably has to do with how terminals support `ncurses`. If it's possible I'll just remove the dependency and render everything with standard `printf`.

**Comment by hilmiwicak** [comment]
Great! Can't wait!

**Comment by BioBox** [comment]
I have a similar problem. The cube works fine in `xterm` but is broken in `urxvt`.

**Comment by leonmavr** [comment]
@BioBox thanks for the feedback. Are you sure it worked on `xterm` and it's broken on `urxvt`? For me it was the other way round lol. Can you let me know what OS you're using? I'm debugging this right now.

**Comment by BioBox** [comment]
I'm using Manjaro I3 with the default terminal settings. I'll show you a picture once I get home.

**Comment by BioBox** [comment]
Here. The one on the right is `urxvt` and the other is `xterm`.
![cube_comparison](https://user-images.githubusercontent.com/34218082/214416320-937df306-becc-427d-b4a0-e070513fa8aa.jpeg)

**Comment by leonmavr** [comment]
Hey @hilmiwicak and @BioBox, can you do a `git pull` and check the output again? ;)

It should be fixed in the latest master.

**Comment by hilmiwicak** [comment]
Nice now it works fine! :)

**Comment by leonmavr** [comment]
Thanks guys, I'm closing it.
